Feature/refactor
MOLi-rocks/MOLi-DoorMonitor pull request #5
Opened 2020-07-02 06:55 UTC by zxp86021

@passerbyid please give a look

2020-07-02 07:58 UTC, x3388638 commented on index.js
> +const devGroupChatId = config.telegramDevGroupChatId;
```suggestion
const {
  firebaseDatabaseURL,
  token,
  cameraURL,
  telegramGroupChatId,
  telegramDevGroupChatId
} = config
```

2020-07-02 08:02 UTC, x3388638 commented on index.js
> +  const port = server.address().port;
unused?

2020-07-02 08:05 UTC, x3388638 commented on index.js
> +  credential: firebaseAdmin.credential.cert(config.firebaseServiceAccountKeyFilePath),
`firebaseServiceAccountKeyFilePath` can also be destructured at line 8

2020-07-02 14:25 UTC, passerbyid commented
Should update README.

2020-07-02 14:28 UTC, YuerLee requested changes
Should update README.

2020-07-03 00:40 UTC, zxp86021 commented
@passerbyid @x3388638 plz give more look (?

2020-07-03 02:25 UTC, x3388638 reviewed
LGTM

2020-07-03 12:22 UTC, YuerLee approved these changes
讚讚

2020-07-03 15:42 UTC, merged